import { ArrowLeft, ArrowRight, RotateCcw } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import Button from '@/components/ui/button'
import GuestCapture from '@/components/guest-capture'
import PageShell from '@/components/page-shell'
import PageTransition from '@/components/page-transition'
import { FramedSurface } from '@/components/event-frame'
import useGuestSubmissionStore from '@/stores/use-guest-submission-store'

const RecordingPage = () => {
  const { accessCode = '' } = useParams(); const navigate = useNavigate(); const state = useGuestSubmissionStore()
  const hasContent = Boolean(state.messageText.trim() || state.media)
  const continueFlow = () => { if (hasContent) navigate(`/invite/${accessCode}/privacy`) }
  return <PageShell><PageTransition><section className="mx-auto max-w-3xl"><div className="mb-5 flex items-center justify-between"><Link to={`/invite/${accessCode}`}><Button variant="ghost" size="sm"><ArrowLeft className="mr-1 h-4 w-4" />Invitación</Button></Link><span className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">1 de 3</span></div><FramedSurface className="p-5 sm:p-9"><div className="text-center"><p className="text-sm font-extrabold uppercase tracking-[.18em] text-[var(--event-primary)]">Tu felicitación</p><h1 className="mt-2 text-3xl font-extrabold text-slate-900 sm:text-4xl">Deja un recuerdo</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-slate-500">Escribe un mensaje si quieres y añade una sola foto, video o nota de voz.</p></div><div className="mt-7"><label className="text-sm font-bold text-slate-700">Mensaje <span className="font-medium text-slate-400">(opcional)</span></label><textarea value={state.messageText} onChange={(event) => state.setMessageText(event.target.value)} placeholder="Escribe algo bonito…" className="mt-2 block min-h-28 w-full resize-none rounded-2xl border border-slate-200 bg-white p-4 text-sm leading-6 text-slate-700 outline-none transition focus:border-violet-300 focus:ring-4 focus:ring-violet-100" /></div><div className="my-7 border-t border-slate-100" /><div><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-bold text-slate-700">Foto, video o audio <span className="font-medium text-slate-400">(opcional)</span></p><p className="mt-1 text-xs text-slate-400">Solo puedes adjuntar un archivo multimedia.</p></div></div>{state.media ? <div className="mx-auto max-w-xl"><div className="overflow-hidden rounded-2xl border border-slate-100 bg-slate-950 shadow-inner">{state.mediaPreviewUrl && state.mediaType === 'image' && <img src={state.mediaPreviewUrl} alt="Previsualización" className="aspect-video w-full object-contain" />}{state.mediaPreviewUrl && state.mediaType === 'video' && <video src={state.mediaPreviewUrl} controls className="aspect-video w-full" />}{state.mediaPreviewUrl && state.mediaType === 'audio' && <div className="flex aspect-video items-center justify-center bg-[var(--event-primary)] p-8"><audio src={state.mediaPreviewUrl} controls className="w-full" /></div>}</div><Button variant="outline" className="mx-auto mt-4" onClick={() => state.setMedia(null)}><RotateCcw className="mr-2 h-4 w-4" />Cambiar multimedia</Button></div> : <GuestCapture onCapture={(file, type) => state.setMedia(file, type)} />}</div><div className="mt-8 flex justify-end"><Button onClick={continueFlow} disabled={!hasContent}>Continuar<ArrowRight className="ml-2 h-4 w-4" /></Button></div></FramedSurface></section></PageTransition></PageShell>
}
export default RecordingPage
